name: Deploy Admin Panel

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          npm install
          npm run build
        env:
          VITE_API_URL: ${{ secrets.ADMIN_API_URL }}
          VITE_GOOGLE_WEB_CLIENT_ID: ${{ secrets.ADMIN_GOOGLE_WEB_CLIENT_ID }}
